//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportJsonFromExcel.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HtmlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExportJsonFromExcel.App_GlobalResources.HtmlResource", typeof(HtmlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img class=&quot;full left lazyload&quot; src=&quot;${src}&quot; alt=&quot;@ViewBag.Title&quot; /&gt;.
        /// </summary>
        public static string HtmlImg {
            get {
                return ResourceManager.GetString("HtmlImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;wrap-chia52hang wrap-chia52hang2 hasshowhide &quot;&gt;
        ///
        ///            &lt;div class=&quot;chia52hang&quot; id=&quot;tr-prd-bottomt${num}&quot;&gt;
        ///
        ///                &lt;div class=&quot;clear&quot;&gt;&lt;/div&gt;
        ///            &lt;/div&gt;
        ///            &lt;img id=&quot;loadMoret${num}&quot; class=&quot;viewMore&quot; src=&quot;https://image.yes24.vn/Upload/Event/2020/btn_Slide/btn_ViewMore_01.png&quot; alt=&quot;@ViewBag.Title&quot;&gt;
        ///            &lt;div class=&quot;clear&quot;&gt;&lt;/div&gt;
        ///        &lt;/div&gt;.
        /// </summary>
        public static string HtmlProductSeeMore {
            get {
                return ResourceManager.GetString("HtmlProductSeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;wrap-chia52hang wrap-chia52hang2 hasshowhide&quot;&gt;
        ///
        ///            &lt;div class=&quot;chia52hang&quot; id=&quot;tr-prd-bottomt${num}&quot;&gt;
        ///
        ///                &lt;div class=&quot;clear&quot;&gt;&lt;/div&gt;
        ///            &lt;/div&gt;
        ///
        ///            &lt;div class=&quot;clear&quot;&gt;&lt;/div&gt;
        ///        &lt;/div&gt;.
        /// </summary>
        public static string HtmlProductSlider {
            get {
                return ResourceManager.GetString("HtmlProductSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;full left&quot; href=&quot;${url}&quot; target=&quot;_blank&quot;&gt;&lt;/a&gt;.
        /// </summary>
        public static string HtmlTag {
            get {
                return ResourceManager.GetString("HtmlTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Globals.Yes24Image/.
        /// </summary>
        public static string Yes24Image {
            get {
                return ResourceManager.GetString("Yes24Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://image.yes24.vn/.
        /// </summary>
        public static string Yes24ImageDomain {
            get {
                return ResourceManager.GetString("Yes24ImageDomain", resourceCulture);
            }
        }
    }
}
